### ISSUE TITLE
Sort-Algorithm for Traders takes about 6-8 seconds

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-functions#5]

**Comment by thecodemonkey** [comment]
I would like to refactor several things in the function but also in the frontend when accessing the function:

1. the function locationByDistance currently has access to the Traders Collection, this is not necessary, because the location.id == Trader.id (This access is probably what the whole performance costs).

2. currently filters by category on the client side. This should actually also be done on the server, so that this works correctly with paging and co.

3. in the current version, as I see the sorting happens on the client side. This doesn't make sense somehow, because the only reason for the FB function was to sort on the server side.

**Comment by christianaschoff** [comment]
sounds good over all.

Aspect 2: I agree in the end, but each filter would require another roundtrip. 
The way it works right now is: it loads the "all" category. So the user has all data anyway. If we establish (real) paging, then I totally agree with you.

**Comment by thecodemonkey** [comment]
I have now extended the function so that all: sorting, filtering and paging mechanisms are exclusively server-side. Especially for filtering by category, the categories have to be stored in the locations additionally. I will implement an additional update routine for this later(It's not a part of this Issue).

**Comment by thecodemonkey** [comment]
category Query is disabled if request.categories are empty. I also added an update script that you can run manually from any dev machine to update the locations. The categories are now stored redundantly, once in the traders and once in the locations. The sync(when saving the TraderProfile) I will implement in the frontend project, this is easier. 

![image](https://user-images.githubusercontent.com/1646017/80499149-e7674700-896c-11ea-86eb-23f5814a4bf1.png)

To perform the update on the respective stage. Simply change the stage enum from DEVELOPMENT to INTEGRATION or PRODUCTION. Furthermore, you need the Secrets, which should be created by everyone under ServiceAccount in Firebase Console => "Generate new private key" and copied into the local folder **secrets** in functions repo. It is a *.json file. The order Secrets is entered in .gitignore and must not be pushed to GitHub!
